# si le pegamos a http://localhost:8071/stockapp-eurekaserver/default - donde default es el perfil, obtenemos la config

spring:
  config:
    import: optional:file:.env[.properties]

server:
  port: ${eurekaport}
  
  
eureka:
  instance:
    hostname: localhost
  client:
    registerWithEureka: false
    fetchRegistry: false
  server:
    waitTimeInMsWhenSyncEmpty: 5
    
management:
  endpoints:
    web:
      exposure:
        include: "*"