server:
  port: 8085
  
management:
  endpoints:
    web:
      exposure:
        include: "*"
        
eureka:
  instance:
    preferIpAddress: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka

logging:
  level:
    root: INFO


spring:
  config:
    import: optional:file:.env[.properties]
  cloud:
    stream:
      kafka:
        binder:
          brokers: localhost:9092
      bindings:
        producerBinding-out-0:
          destination: stock-topic
        consumerBinding-in-0:
          destination: stock-topic
    function:
      definition: producerBinding,consumerBinding
  integration:
    poller:
      fixed-delay: 2000
      initial-delay: 10000

apikey:
  value: ${apikey}
