# si le pegamos a http://localhost:8071/stockapp-eurekaserver/default - donde default es el perfil, obtenemos la config

server:
  port: 8761
  
  
eureka:
  instance:
    hostname: localhost
  client:
    registerWithEureka: false
    fetchRegistry: false
  server:
    waitTimeInMsWhenSyncEmpty: 5
    

#management.endpoints.web.exposure.include=*