
server:
  port: 8072
  



management:
  endpoints:
    web:
      exposure:
        include: "*"
        
        
eureka:
  instance:
    preferIpAddress: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka

        
spring:
  cloud:
    loadbalancer.ribbon.enabled: false
    gateway:
        discovery:
          locator:
            enabled: true
            lower-case-service-id: true
        routes:
        - id: stockapp-frontserver
          uri: lb://stockapp-frontserver
          predicates:
          - Path=/front/**
          filters:
          - RewritePath=/front/(?<path>.*), /$\{path}
        - id: stockapp-apiconnection
          uri: lb://stockapp-apiconnection
          predicates:
          - Path=/apiconnection/**
          filters:
          - RewritePath=/apiconnection/(?<path>.*), /$\{path}

logging:
  level:
    com.netflix: WARN
    org.springframework.web: WARN
    com.stockapp.gateway: DEBUG

