spring:
  application:
    name: stockapp-configserver    # important for Service Discovery!
  profiles:
    active: git  
  cloud:
    config:
      server:
        #Local configuration: This locations can either of classpath or locations in the filesystem.
        #native:
          #search-locations: classpath:/config
          # The classpath attribute causes Spring Cloud Config Server to look in the src/main/resources/config folder.
        git:
          uri: https://github.com/pedrofanelli/stockapp-configserver.git
          searchPaths: src/main/resources/config
  # para extraer variables de file .env
  config:
    import: optional:file:.env[.properties]

# POST localhost:8071/encrypt /decrypt + en body/raw el dato
# esta key la necesitamos para que funcione! para que encripte lo que pasamos
encrypt:
  key: ${encryptkey}
  

server:
  port: 8071
  
logging:
  level:
    web: DEBUG